# Generated by Django 5.0.1 on 2026-08-24 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="click",
            name="url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to="links.url",
            ),
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(
                fields=["clicked_at"], name="analytics_c_clicked_a3ae6d_idx"
            ),
        ),
    ]
