repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
        files: ^CLEAN_CODE_TESTING_GIT/weather-api-stub/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args: [--fix]
        files: ^CLEAN_CODE_TESTING_GIT/weather-api-stub/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies: [pytest, pytest-mock]
        files: ^CLEAN_CODE_TESTING_GIT/weather-api-stub/
