repos:
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        files: ^CLEAN_CODE_TESTING_GIT/secure-service-module/(src|tests)/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        files: ^CLEAN_CODE_TESTING_GIT/secure-service-module/(src|tests)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.2
    hooks:
      - id: mypy
        files: ^CLEAN_CODE_TESTING_GIT/secure-service-module/src/
        args: [--explicit-package-bases, --ignore-missing-imports]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: cmd /c "cd CLEAN_CODE_TESTING_GIT\secure-service-module && python -m pytest"
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
