repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.284
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--explicit-package-bases, --ignore-missing-imports]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: cmd /c "C:\Users\patri\OneDrive\Desktop\AmaliTech\AmaliTech_Python_Backend_Labs\CLEAN_CODE_TESTING_GIT\secure-service-module\run_tests.bat"
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
