openapi: 3.0.3
info:
  title: URL Shortener API
  version: 1.0.0
  description: URL shortener microservice built with Django REST Framework
paths:
  /{short_code}/:
    get:
      operationId: root_retrieve
      description: Redirect to the original URL
      parameters:
      - in: path
        name: short_code
        schema:
          type: string
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '302':
          description: No response body
        '404':
          description: No response body
  /shorten/:
    post:
      operationId: shorten_create
      description: Create a new shortened URL
      tags:
      - shorten
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UrlCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UrlCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Url'
          description: ''
components:
  schemas:
    Url:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        original_url:
          type: string
          format: uri
          maxLength: 2000
        short_url:
          type: string
          readOnly: true
        short_link:
          type: string
          format: uri
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - original_url
      - short_link
      - short_url
    UrlCreate:
      type: object
      properties:
        original_url:
          type: string
          format: uri
          maxLength: 2000
      required:
      - original_url
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
