# Generated by Django 5.0.1 on 2026-08-31 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortener", "0002_seed_default_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="clicked_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
