# Generated by Django 5.0.1 on 2026-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "url_shortener",
            "0002_tag_url_click_count_url_custom_alias_url_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
