"""Protocols for Postgres-backed repositories. Services depend only on
these, never on psycopg2 directly. `cursor` is typed `Any` on purpose: this
module must not import a driver just to name its cursor type.
"""
from __future__ import annotations

from typing import Any, Mapping, Optional, Protocol, Sequence

from social.models import Comment, Follower, Like, Post, User


class UserRepository(Protocol):
    def create(self, cursor: Any, user: User) -> User: ...

    def get_by_id(self, cursor: Any, user_id: int) -> Optional[User]: ...

    def get_by_username(self, cursor: Any, username: str) -> Optional[User]: ...

    def get_by_email(self, cursor: Any, email: str) -> Optional[User]: ...

    def list_all(self, cursor: Any) -> Sequence[User]: ...

    def update_profile(
        self, cursor: Any, user_id: int, full_name: str, bio: str
    ) -> Optional[User]: ...


class PostRepository(Protocol):
    def create(self, cursor: Any, post: Post) -> Post: ...

    def get_by_id(self, cursor: Any, post_id: int) -> Optional[Post]: ...

    def delete(self, cursor: Any, post_id: int) -> None: ...

    def list_recent(self, cursor: Any, limit: int) -> Sequence[Post]: ...


class CommentRepository(Protocol):
    def create(self, cursor: Any, comment: Comment) -> Comment: ...

    def list_by_post(self, cursor: Any, post_id: int) -> Sequence[Comment]: ...

    def count_by_posts(self, cursor: Any, post_ids: Sequence[int]) -> Mapping[int, int]: ...


class FollowerRepository(Protocol):
    def create(self, cursor: Any, follower_id: int, followee_id: int) -> Follower: ...

    def exists(self, cursor: Any, follower_id: int, followee_id: int) -> bool: ...

    def delete(self, cursor: Any, follower_id: int, followee_id: int) -> bool: ...

    def list_following(self, cursor: Any, follower_id: int) -> Sequence[int]: ...

    def list_followers(self, cursor: Any, followee_id: int) -> Sequence[int]: ...


class LikeRepository(Protocol):
    def create(self, cursor: Any, user_id: int, post_id: int) -> Like: ...

    def exists(self, cursor: Any, user_id: int, post_id: int) -> bool: ...

    def count_by_posts(self, cursor: Any, post_ids: Sequence[int]) -> Mapping[int, int]: ...


class FeedRepository(Protocol):
    def get_timeline(self, cursor: Any, follower_id: int, limit: int) -> Sequence[Post]: ...
